// Generated by IB v0.3.5 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError
@end

@implementation NSNotificationCenter
@end

@implementation NSURLRequest
@end

@implementation Camera
@end

@implementation UIAlertView
@end

@implementation ClickedButton
@end

@implementation InvalidURLError
@end

@implementation InvalidFileError
@end

@implementation NSMutableURLRequest
@end

@implementation NSString
@end

@implementation NSURL
@end

@implementation UIImageView
@end

@implementation HTTPResult
@end

@implementation ClientDSL
@end

@implementation AFHTTPClient
@end

@implementation HeaderWrapper
@end

@implementation UIImage
@end

@implementation AnimationChain
@end

@implementation UIView
@end

@implementation Anonymous
@end

@implementation NSObject
@end

@implementation NSDictionary
@end

@implementation AnonymousArray
@end

@implementation NSArray
@end

@implementation NSString
@end

@implementation NSMutableString
@end

@implementation NSAttributedString
@end

@implementation NSMutableAttributedString
@end

@implementation Symbol
@end

@implementation Fixnum
@end

@implementation NSArray
@end

@implementation NSString
@end

@implementation Symbol
@end

@implementation UIColor
@end

@implementation UIImage
@end

@implementation Symbol
@end

@implementation SugarCubeNotFoundException
@end

@implementation NSError
@end

@implementation NSIndexPath
@end

@implementation NSLayoutConstraint
@end

@implementation NSNotification
@end

@implementation NSSet
@end

@implementation NSURL
@end

@implementation UIColor
@end

@implementation UIEvent
@end

@implementation UILabel
@end

@implementation UITextField
@end

@implementation UITouch
@end

@implementation UIView
@end

@implementation UIViewController
@end

@implementation CLLocationCoordinate2D
@end

@implementation UIControl
@end

@implementation UITextView
@end

@implementation UIActionSheet
@end

@implementation UIActivityIndicatorView
@end

@implementation UIAlertView
@end

@implementation UIBarButtonItem
@end

@implementation UIButton
@end

@implementation UISegmentedControl
@end

@implementation NSString
@end

@implementation NSArray
@end

@implementation NSIndexPath
@end

@implementation NSIndexSet
@end

@implementation NSString
@end

@implementation NSURL
@end

@implementation UIView
@end

@implementation CIColor
@end

@implementation CIFilter
@end

@implementation CIImage
@end

@implementation UIColor
@end

@implementation UIImage
@end

@implementation IndexPath
@end

@implementation NSError
@end

@implementation NSCoder
@end

@implementation NSData
@end

@implementation NSString
@end

@implementation NSURL
@end

@implementation Numeric
@end

@implementation String
@end

@implementation Fixnum
@end

@implementation NSDate
@end

@implementation NSString
@end

@implementation NSUserDefaults
@end

@implementation Object
@end

@implementation NilClass
@end

@implementation NSArray
@end

@implementation NSDictionary
@end

@implementation Fixnum
@end

@implementation NSString
@end

@implementation Numeric
@end

@implementation NSArray
@end

@implementation NSAttributedString
@end

@implementation NSString
@end

@implementation Symbol
@end

@implementation UIImage
@end

@implementation UILabel
@end

@implementation UIView
@end

@implementation UIViewController
@end

@implementation UINavigationController
@end

@implementation UITabBarController
@end

@implementation UIWebView
@end

@implementation Symbol
@end

@implementation NSString
@end

@implementation AppDelegate
@end

@implementation AppuntiController
@end

@implementation AppuntoFormController
@end

@implementation AppuntoModalController
@end

@implementation ClienteDetailController
@end

@implementation ClientiController
@end

@implementation DetailController
@end

@implementation DynamicController
@end

@implementation DynamicNewController
@end

@implementation EditPrezzoViewController
@end

@implementation EditReminderController
@end

@implementation EditStatoViewController
@end

@implementation EditTextViewController
@end

@implementation LibriController
@end

@implementation MainController
@end

@implementation MenuController
@end

@implementation RigaFormController
@end

@implementation SearchClienteController
@end

@implementation ImporterResult
@end

@implementation DataImporter
@end

@implementation EKEventEditViewController
@end

@implementation NSArray
@end

@implementation NSEntityDescription
@end

@implementation NSIndexPath
@end

@implementation NSManagedObject
@end

@implementation NSManagedObject
@end

@implementation NSManagedObject
@end

@implementation Time
@end

@implementation UIBarButtonItemPlain
@end

@implementation UIBarButtonItemEdit
@end

@implementation UIBarButtonItemAdd
@end

@implementation UIBarButtonItemDone
@end

@implementation UIBarButtonItemCancel
@end

@implementation UINavigationControllerDoneCancel
@end

@implementation UITableView
@end

@implementation UITableViewCell
@end

@implementation UITableViewController
@end

@implementation UITableViewControllerForNSManagedObject
@end

@implementation UITableViewTextFieldCell
@end

@implementation UITableViewTextViewCell
@end

@implementation UIView
@end

@implementation MappingProvider
@end

@implementation Adozione
@end

@implementation Appunto
@end

@implementation Classe
@end

@implementation Cliente
@end

@implementation Coordinates
@end

@implementation Docente
@end

@implementation Libro
@end

@implementation Riga
@end

@implementation Store
@end

@implementation AppuntoCell
@end

@implementation AppuntoCellAuto
@end

@implementation ClienteCell
@end

@implementation LibroCell
@end

@implementation RigaCell
@end

@implementation CircleButton
@end

