// Generated by IB v0.3.5 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface ParserError: StandardError
@end

@interface NSNotificationCenter
-(IBAction) observers;
-(IBAction) unobserve:(id) observer;

@end

@interface NSURLRequest
-(IBAction) to_s;

@end

@interface Camera
-(IBAction) initialize:(id) location;
-(IBAction) location;
-(IBAction) imagePickerControllerDidCancel:(id) picker;
-(IBAction) picker;
-(IBAction) dismiss;
-(IBAction) camera_device;
-(IBAction) media_type_to_symbol:(id) media_type;
-(IBAction) symbol_to_media_type:(id) symbol;
-(IBAction) error:(id) type;

@end

@interface UIAlertView
-(IBAction) style;
-(IBAction) cancel_button_index;

@end

@interface ClickedButton
-(IBAction) willPresentAlertView:(id) alert;
-(IBAction) didPresentAlertView:(id) alert;
-(IBAction) alertViewCancel:(id) alert;
-(IBAction) alertViewShouldEnableFirstOtherButton:(id) alert;
-(IBAction) plain_text_field;
-(IBAction) secure_text_field;
-(IBAction) login_text_field;
-(IBAction) password_text_field;

@end

@interface InvalidURLError: StandardError
@end

@interface InvalidFileError: StandardError
@end

@interface NSMutableURLRequest
-(IBAction) url;
-(IBAction) content_type;
-(IBAction) parameters;

@end

@interface NSString
-(IBAction) to_url;

@end

@interface NSURL
-(IBAction) to_url;

@end

@interface UIImageView
-(IBAction) url;

@end

@interface HTTPResult
-(IBAction) body;

@end

@interface ClientDSL
-(IBAction) initialize:(id) client;
-(IBAction) authorization:(id) options;
-(IBAction) operation:(id) operation;
-(IBAction) parameter_encoding:(id) encoding;

@end

@interface AFHTTPClient
-(IBAction) authorization;
-(IBAction) initialize:(id) client;
-(IBAction) delete:(id) header;
-(IBAction) headers;
-(IBAction) dummy;

@end

@interface HeaderWrapper
-(IBAction) initialize:(id) client;
-(IBAction) delete:(id) header;
-(IBAction) headers;
-(IBAction) dummy;

@end

@interface UIImage
-(IBAction) imageNamed568:(id) name;
-(IBAction) imageNamed:(id) name;

@end

@interface AnimationChain
-(IBAction) chains;
-(IBAction) start_chain:(id) chain;
-(IBAction) stop_chain:(id) chain;
-(IBAction) initialize;
-(IBAction) wait:(id) duration;
-(IBAction) do_next;
-(IBAction) start;
-(IBAction) loop:(id) times;
-(IBAction) stop;
-(IBAction) abort;

@end

@interface UIView
-(IBAction) show;
-(IBAction) hide;
-(IBAction) shake:(id) options;
-(IBAction) dummy;

@end

@interface Anonymous: Hash
-(IBAction) to_object;
-(IBAction) each;

@end

@interface NSObject
-(IBAction) to_object;

@end

@interface NSDictionary
-(IBAction) to_object;

@end

@interface AnonymousArray: Array
-(IBAction) first;
-(IBAction) last;
-(IBAction) to_object;

@end

@interface NSArray
-(IBAction) to_object;

@end

@interface NSString
-(IBAction) bold:(id) size;
-(IBAction) italic:(id) size;
-(IBAction) monospace:(id) size;
-(IBAction) underline:(id) underline_style;
-(IBAction) nsattributedstring:(id) attributes;

@end

@interface NSMutableString
-(IBAction) nsattributedstring:(id) attributes;
-(IBAction) dummy;

@end

@interface NSAttributedString
-(IBAction) dummy;
-(IBAction) to_s;
-(IBAction) bold:(id) size;
-(IBAction) italic:(id) size;
-(IBAction) underline;
-(IBAction) font:(id) value;
-(IBAction) paragraph_style:(id) value;
-(IBAction) foreground_color:(id) value;
-(IBAction) underline_style:(id) value;
-(IBAction) background_color:(id) value;
-(IBAction) ligature:(id) value;
-(IBAction) kern:(id) value;
-(IBAction) stroke_width:(id) value;
-(IBAction) stroke_color:(id) value;
-(IBAction) strikethrough_style:(id) value;
-(IBAction) shadow:(id) value;
-(IBAction) vertical_glyph_form:(id) value;
-(IBAction) with_attributes:(id) attributes;
-(IBAction) nsattributedstring;

@end

@interface NSMutableAttributedString
-(IBAction) with_attributes:(id) attributes;

@end

@interface Symbol
-(IBAction) awesome_icon:(id) options;

@end

@interface Fixnum
-(IBAction) uicolor:(id) alpha;

@end

@interface NSArray
-(IBAction) uicolor:(id) alpha;

@end

@interface NSString
-(IBAction) uicolor:(id) alpha;

@end

@interface Symbol
-(IBAction) uicolor:(id) alpha;

@end

@interface UIColor
-(IBAction) uicolor:(id) alpha;
-(IBAction) cgcolor;
-(IBAction) invert;
-(IBAction) red;
-(IBAction) green;
-(IBAction) blue;
-(IBAction) alpha;
-(IBAction) to_i;
-(IBAction) to_a;
-(IBAction) hex;
-(IBAction) css_name;
-(IBAction) system_name;

@end

@interface UIImage
-(IBAction) uicolor:(id) alpha;

@end

@interface Symbol
-(IBAction) uidevice;
-(IBAction) uideviceorientation;
-(IBAction) uiinterfaceorientation;
-(IBAction) uiinterfacemask;
-(IBAction) uiautoresizemask;
-(IBAction) uireturnkey;
-(IBAction) uikeyboardtype;
-(IBAction) uitextalignment;
-(IBAction) uilinebreakmode;
-(IBAction) uibaselineadjustment;
-(IBAction) uibordertype;
-(IBAction) nsdatestyle;
-(IBAction) nsnumberstyle;
-(IBAction) uistatusbarstyle;
-(IBAction) uibarmetrics;
-(IBAction) uibarbuttonitem;
-(IBAction) uibarbuttonstyle;
-(IBAction) uibuttontype;
-(IBAction) uicontrolstate;
-(IBAction) uicontrolevent;
-(IBAction) uiactivityindicatorstyle;
-(IBAction) uisegmentedstyle;
-(IBAction) uidatepickermode;
-(IBAction) uicontentmode;
-(IBAction) uianimationcurve;
-(IBAction) uitablestyle;
-(IBAction) uitablerowanimation;
-(IBAction) uitablecellstyle;
-(IBAction) uitablecellaccessorytype;
-(IBAction) uitablecellselectionstyle;
-(IBAction) uitablecellseparatorstyle;
-(IBAction) uialertstyle;
-(IBAction) uiactionstyle;
-(IBAction) uiimagesource;
-(IBAction) uiimagecapture;
-(IBAction) uiimagecamera;
-(IBAction) uiimagequality;
-(IBAction) catimingfunction;
-(IBAction) cglinecap;
-(IBAction) cglinejoin;
-(IBAction) uigesturerecognizerstate;

@end

@interface SugarCubeNotFoundException: Exception
@end

@interface NSError
-(IBAction) to_s;

@end

@interface NSIndexPath
-(IBAction) to_s;

@end

@interface NSLayoutConstraint
-(IBAction) to_s;

@end

@interface NSNotification
-(IBAction) to_s;
-(IBAction) inspect;

@end

@interface NSSet
-(IBAction) to_s;

@end

@interface NSURL
-(IBAction) to_s;
-(IBAction) inspect;

@end

@interface UIColor
-(IBAction) to_s;
-(IBAction) inspect;

@end

@interface UIEvent
-(IBAction) to_s;

@end

@interface UILabel
-(IBAction) to_s:(id) options;

@end

@interface UITextField
-(IBAction) to_s:(id) options;

@end

@interface UITouch
-(IBAction) to_s;

@end

@interface UIView
-(IBAction) to_s:(id) options;

@end

@interface UIViewController
-(IBAction) to_s;

@end

@interface CLLocationCoordinate2D
-(IBAction) distance_to:(id) cl_location_2d;

@end

@interface UIControl
-(IBAction) sugarcube_callbacks;
-(IBAction) call;

@end

@interface UITextView
-(IBAction) sugarcube_callbacks;

@end

@interface UIActionSheet
-(IBAction) dummy;

@end

@interface UIActivityIndicatorView
-(IBAction) large;
-(IBAction) white;
-(IBAction) gray;

@end

@interface UIAlertView
-(IBAction) dummy;

@end

@interface UIBarButtonItem
-(IBAction) sugarcube_handle_action:(id) sender;

@end

@interface UIButton
-(IBAction) custom;
-(IBAction) rounded;
-(IBAction) rounded_rect;
-(IBAction) detail;
-(IBAction) detail_disclosure;
-(IBAction) info;
-(IBAction) info_light;
-(IBAction) info_dark;
-(IBAction) contact;
-(IBAction) contact_add;

@end

@interface UISegmentedControl
-(IBAction) plain:(id) items;
-(IBAction) bordered:(id) items;
-(IBAction) bar:(id) items;
-(IBAction) bezeled:(id) items;

@end

@interface NSString
-(IBAction) document;
-(IBAction) cache;
-(IBAction) app_support;
-(IBAction) resource;
-(IBAction) resource_url;
-(IBAction) info_plist;

@end

@interface NSArray
-(IBAction) nsindexpath;
-(IBAction) nsindexset;
-(IBAction) nsset;

@end

@interface NSIndexPath
-(IBAction) to_a;

@end

@interface NSIndexSet
-(IBAction) to_a;

@end

@interface NSString
-(IBAction) nsurl;
-(IBAction) fileurl;
-(IBAction) escape_url;
-(IBAction) unescape_url;

@end

@interface NSURL
-(IBAction) open;
-(IBAction) nsurlrequest;
-(IBAction) nsmutableurlrequest;

@end

@interface UIView
-(IBAction) off_gestures;
-(IBAction) sugarcube_handle_gesture:(id) recognizer;

@end

@interface CIColor
-(IBAction) cicolor;

@end

@interface CIFilter
-(IBAction) uiimage;
-(IBAction) ciimage;
-(IBAction) color_invert;
-(IBAction) mask_to_alpha;
-(IBAction) maximum_component;
-(IBAction) minimum_component;
-(IBAction) random_generator;

@end

@interface CIImage
-(IBAction) ciimage;
-(IBAction) apply_filter:(id) filter;

@end

@interface UIColor
-(IBAction) cicolor;

@end

@interface UIImage
-(IBAction) crop:(id) rect;
-(IBAction) in_rect:(id) rect;
-(IBAction) scale_to_fill:(id) new_size;
-(IBAction) scale_within:(id) new_size;
-(IBAction) scale_to:(id) new_size;
-(IBAction) rounded:(id) corner_radius;
-(IBAction) apply_filter:(id) filter;
-(IBAction) cgimage;
-(IBAction) ciimage;
-(IBAction) darken:(id) options;
-(IBAction) rotate:(id) angle_or_direction;
-(IBAction) tileable:(id) insets;
-(IBAction) stretchable:(id) insets;
-(IBAction) alignment_rect:(id) insets;
-(IBAction) masked:(id) mask_image;
-(IBAction) color_at:(id) point;
-(IBAction) at_scale:(id) scale;

@end

@interface IndexPath
-(IBAction) initialize:(id) values;

@end

@interface NSError
-(IBAction) localized;

@end

@interface NSCoder
-(IBAction) bool:(id) key;
-(IBAction) double:(id) key;
-(IBAction) float:(id) key;
-(IBAction) int:(id) key;
-(IBAction) point:(id) key;
-(IBAction) rect:(id) key;
-(IBAction) size:(id) key;

@end

@interface NSData
-(IBAction) nsstring:(id) encoding;
-(IBAction) uiimage:(id) scale;

@end

@interface NSString
-(IBAction) nsdata:(id) encoding;

@end

@interface NSURL
-(IBAction) nsdata;

@end

@interface Numeric
-(IBAction) milliseconds;
-(IBAction) in_milliseconds;
-(IBAction) seconds;
-(IBAction) in_seconds;
-(IBAction) minutes;
-(IBAction) in_minutes;
-(IBAction) hours;
-(IBAction) in_hours;
-(IBAction) days;
-(IBAction) in_days;
-(IBAction) weeks;
-(IBAction) in_weeks;
-(IBAction) months;
-(IBAction) in_months;
-(IBAction) years;
-(IBAction) in_years;

@end

@interface String
-(IBAction) to_date;
-(IBAction) to_timezone;
-(IBAction) to_duration;

@end

@interface Fixnum
-(IBAction) nstimezone;
-(IBAction) before:(id) date;
-(IBAction) ago;
-(IBAction) after:(id) date;
-(IBAction) hence;

@end

@interface NSDate
-(IBAction) string_with_format:(id) format;
-(IBAction) timezone;
-(IBAction) era;
-(IBAction) utc_offset;
-(IBAction) date_array;
-(IBAction) time_array;
-(IBAction) datetime_array;
-(IBAction) start_of_day;
-(IBAction) end_of_day;
-(IBAction) start_of_week:(id) start_day;
-(IBAction) end_of_week:(id) start_day;
-(IBAction) start_of_month;
-(IBAction) end_of_month;
-(IBAction) days_in_month;
-(IBAction) days_in_year;
-(IBAction) days_to_week_start:(id) start_day;
-(IBAction) local_week_start;
-(IBAction) week_day_index:(id) week_day;

@end

@interface NSString
-(IBAction) nstimezone;

@end

@interface NSUserDefaults
-(IBAction) remove:(id) key;

@end

@interface Object
-(IBAction) to_nsuserdefaults;

@end

@interface NilClass
-(IBAction) to_nsuserdefaults;

@end

@interface NSArray
-(IBAction) to_nsuserdefaults;

@end

@interface NSDictionary
-(IBAction) to_nsuserdefaults;

@end

@interface Fixnum
-(IBAction) nth;
-(IBAction) ordinalize;

@end

@interface NSString
-(IBAction) to_number;

@end

@interface Numeric
-(IBAction) percent;
-(IBAction) g;
-(IBAction) in_g;
-(IBAction) radians;
-(IBAction) in_radians;
-(IBAction) degrees;
-(IBAction) in_degrees;
-(IBAction) pi;
-(IBAction) meters;
-(IBAction) in_meters;
-(IBAction) kilometers;
-(IBAction) in_kilometers;
-(IBAction) miles;
-(IBAction) in_miles;
-(IBAction) feet;
-(IBAction) in_feet;
-(IBAction) bytes;
-(IBAction) kilobytes;
-(IBAction) megabytes;
-(IBAction) gigabytes;
-(IBAction) terabytes;
-(IBAction) petabytes;
-(IBAction) exabytes;
-(IBAction) in_bytes;
-(IBAction) in_kilobytes;
-(IBAction) in_megabytes;
-(IBAction) in_gigabytes;
-(IBAction) in_terabytes;
-(IBAction) in_petabytes;
-(IBAction) in_exabytes;
-(IBAction) string_with_style:(id) style;

@end

@interface NSArray
-(IBAction) to_pointer:(id) type;

@end

@interface NSAttributedString
-(IBAction) uilabel;

@end

@interface NSString
-(IBAction) uiimage;
-(IBAction) uifont:(id) size;
-(IBAction) uilabel:(id) font;
-(IBAction) uiimageview;

@end

@interface Symbol
-(IBAction) uifont:(id) size;
-(IBAction) uifontsize;

@end

@interface UIImage
-(IBAction) uiimageview;

@end

@interface UILabel
-(IBAction) fit_to_size:(id) max_size;

@end

@interface UIView
-(IBAction) first_responder;
-(IBAction) unshift:(id) view;
-(IBAction) controller;
-(IBAction) uiimage:(id) use_content_size;
-(IBAction) convert_bounds:(id) destination;
-(IBAction) convert_origin:(id) destination;

@end

@interface UIViewController
-(IBAction) push:(id) view_controller;
-(IBAction) pop;

@end

@interface UINavigationController
-(IBAction) push:(id) view_controller;
-(IBAction) pop:(id) to_view;

@end

@interface UITabBarController
-(IBAction) push:(id) view_controller;

@end

@interface UIWebView
-(IBAction) eval_js:(id) str;

@end

@interface Symbol
-(IBAction) ivar;
-(IBAction) setter;
-(IBAction) cvar;

@end

@interface NSString
-(IBAction) ivar;
-(IBAction) setter;
-(IBAction) cvar;

@end

@interface AppDelegate
-(IBAction) window;
-(IBAction) initAppearance;

@end

@interface AppuntiController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) viewDidDisappear:(id) animated;
-(IBAction) contentSizeCategoryChanged:(id) notification;
-(IBAction) reload;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) loadFromBackend;

@end

@interface AppuntoFormController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) changes:(id) sender;
-(IBAction) didSave:(id) sender;
-(IBAction) save2:(id) sender;
-(IBAction) cancel:(id) sender;
-(IBAction) save:(id) sender;
-(IBAction) cancel2:(id) sender;
-(IBAction) print_appunto;
-(IBAction) documentInteractionControllerViewControllerForPreview:(id) controller;
-(IBAction) numberOfSectionsInTableView:(id) tableView;

@end

@interface AppuntoModalController: UIViewController
-(IBAction) close:(id) sender;

@end

@interface ClienteDetailController: UIViewController

@property IBOutlet id tableView;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) contentSizeCategoryChanged:(id) notification;
-(IBAction) reload;
-(IBAction) appunti_da_fare;
-(IBAction) appunti_in_sospeso;
-(IBAction) appunti_completati;
-(IBAction) sorted_appunti;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) navigate:(id) sender;
-(IBAction) makeCall:(id) sender;
-(IBAction) sendEmail:(id) sender;
-(IBAction) loadFromBackend;

@end

@interface ClientiController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) contentSizeCategoryChanged:(id) notification;
-(IBAction) reload;
-(IBAction) changeMode:(id) sender;
-(IBAction) scrollToClienteAndPush:(id) cliente;
-(IBAction) buttonTappedAction:(id) sender;
-(IBAction) fetchControllerForTableView:(id) tableView;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) loadFromBackend;

@end

@interface DetailController: UIViewController

@property IBOutlet id labelTitolo;
@property IBOutlet id labelSottotitolo;
@property IBOutlet id headerView;

-(IBAction) viewDidLoad;
-(IBAction) scrollToTop;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) changeTitolo:(id) notification;
-(IBAction) loadData;

@end

@interface DynamicController: UIViewController

@property IBOutlet id fakeTableView;

-(IBAction) viewDidLoad;
-(IBAction) handleTap:(id) gesture;
-(IBAction) handlePan:(id) gesture;
-(IBAction) itemBehaviourForView:(id) view;
-(IBAction) tryDockView:(id) view;
-(IBAction) fetchControllerForTableView:(id) tableView;
-(IBAction) searchBarShouldBeginEditing:(id) searchBar;
-(IBAction) searchBarShouldEndEditing:(id) searchBar;
-(IBAction) searchDisplayControllerWillBeginSearch:(id) controller;
-(IBAction) searchDisplayControllerDidEndSearch:(id) controller;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) buttonTappedAction:(id) sender;

@end

@interface DynamicNewController: UIViewController

@property IBOutlet id fakeTableView;

-(IBAction) viewDidLoad;
-(IBAction) handleTap:(id) gesture;
-(IBAction) handlePan:(id) gesture;
-(IBAction) itemBehaviourForView:(id) view;
-(IBAction) tryDockView:(id) view;
-(IBAction) fetchControllerForTableView:(id) tableView;
-(IBAction) searchBarShouldBeginEditing:(id) searchBar;
-(IBAction) searchBarShouldEndEditing:(id) searchBar;
-(IBAction) searchDisplayControllerWillBeginSearch:(id) controller;
-(IBAction) searchDisplayControllerDidEndSearch:(id) controller;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) buttonTappedAction:(id) sender;

@end

@interface EditPrezzoViewController: UITableViewController

@property IBOutlet id editPrezzo;
@property IBOutlet id editSconto;

-(IBAction) viewWillAppear:(id) animated;
-(IBAction) prezzi;
-(IBAction) sconti;
-(IBAction) load_data;
-(IBAction) handleButtonDone;
-(IBAction) showDoneButton:(id) sender;
-(IBAction) done:(id) sender;
-(IBAction) close:(id) sender;

@end

@interface EditReminderController: UIViewController

@property IBOutlet id titleText;
@property IBOutlet id dateButton;
@property IBOutlet id tableView;

-(IBAction) init;
-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) handleReminderCompletion;
-(IBAction) performEventOperations;
-(IBAction) performReminderOperations;
-(IBAction) dismiss;
-(IBAction) show_date_picker;
-(IBAction) pick_date;
-(IBAction) close_date_picker;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) setup_date_picker;

@end

@interface EditStatoViewController: UITableViewController
-(IBAction) close:(id) sender;

@end

@interface EditTextViewController: UIViewController

@property IBOutlet id textView;
@property IBOutlet id textField;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) handleTextCompletion;
-(IBAction) done:(id) sender;
-(IBAction) cancel:(id) sender;
-(IBAction) textFieldShouldReturn:(id) textField;

@end

@interface LibriController: UIViewController

@property IBOutlet id tableView;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) reload;
-(IBAction) close:(id) sender;
-(IBAction) fetchControllerForTableView:(id) tableView;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) loadFromBackend;

@end

@interface MainController: UIViewController

@property IBOutlet id menuView;
@property IBOutlet id detailView;

-(IBAction) viewDidLoad;
-(IBAction) preferredStatusBarStyle;
-(IBAction) importa:(id) sender;
-(IBAction) login:(id) sender;
-(IBAction) esegui_importazione;

@end

@interface MenuController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) ricalcola;
-(IBAction) nel_baule_count;
-(IBAction) in_sospeso_count;
-(IBAction) da_fare_count;
-(IBAction) tutti_count;

@end

@interface RigaFormController: UITableViewController

@property IBOutlet id editQuantita;
@property IBOutlet id editPrezzo;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) load_riga;
-(IBAction) save:(id) sender;
-(IBAction) cancel:(id) sender;

@end

@interface SearchClienteController: UIViewController

@property IBOutlet id fakeTableView;
@property IBOutlet id menuContainer;

-(IBAction) viewDidLoad;
-(IBAction) fetchControllerForTableView:(id) tableView;
-(IBAction) searchDisplayControllerWillBeginSearch:(id) controller;
-(IBAction) searchDisplayControllerDidEndSearch:(id) controller;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) buttonTappedAction:(id) sender;

@end

@interface ImporterResult
-(IBAction) body;

@end

@interface DataImporter
-(IBAction) sync_appunti;

@end

@interface EKEventEditViewController
-(IBAction) saveEvent;
-(IBAction) removeEvent;

@end

@interface NSArray
-(IBAction) to_ip;
-(IBAction) mean;
-(IBAction) to_json;

@end

@interface NSEntityDescription
-(IBAction) wireRelationships;

@end

@interface NSIndexPath
-(IBAction) to_a;

@end

@interface NSManagedObject
-(IBAction) to_cells:(id) delegate;
-(IBAction) from_cells:(id) cells;

@end

@interface NSManagedObject
-(IBAction) refresh_backend;
-(IBAction) update;
-(IBAction) remove;
-(IBAction) persist;
-(IBAction) managedObjectClass;

@end

@interface NSManagedObject
-(IBAction) from_json:(id) json;
-(IBAction) to_json;
-(IBAction) to_json_raw;
-(IBAction) to_json_attr:(id) attr;
-(IBAction) to_json_rel:(id) rel;

@end

@interface Time
-(IBAction) year;
-(IBAction) days_to:(id) other;
-(IBAction) days_add:(id) days;

@end

@interface UIBarButtonItemPlain: UIBarButtonItem
@end

@interface UIBarButtonItemEdit: UIBarButtonItem
@end

@interface UIBarButtonItemAdd: UIBarButtonItem
@end

@interface UIBarButtonItemDone: UIBarButtonItem
@end

@interface UIBarButtonItemCancel: UIBarButtonItem
@end

@interface UINavigationControllerDoneCancel: UINavigationController
@end

@interface UITableView
-(IBAction) updates;

@end

@interface UITableViewCell
-(IBAction) title;
-(IBAction) subtitle;
-(IBAction) tick:(id) aBoolean;
-(IBAction) disclose:(id) aBoolean;
-(IBAction) clear;

@end

@interface UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) keyboardDidShow:(id) notification;
-(IBAction) keyboardWillHide:(id) notification;

@end

@interface UITableViewControllerForNSManagedObject: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) updateObject;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) sections;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) textFieldShouldReturn:(id) textField;

@end

@interface UITableViewTextFieldCell: UITableViewCell
-(IBAction) textField;
-(IBAction) value;
-(IBAction) clear;
-(IBAction) layoutSubviews;

@end

@interface UITableViewTextViewCell: UITableViewCell
-(IBAction) textView;
-(IBAction) value;
-(IBAction) clear;
-(IBAction) layoutSubviews;

@end

@interface UIView
-(IBAction) firstResponder;
-(IBAction) viewController;

@end

@interface MappingProvider
-(IBAction) libro_mapping;
-(IBAction) request_libro_mapping;
-(IBAction) cliente_mapping;
-(IBAction) request_cliente_mapping;
-(IBAction) appunto_mapping;
-(IBAction) request_appunto_mapping;
-(IBAction) request_riga_mapping;
-(IBAction) riga_mapping;
-(IBAction) classe_mapping;
-(IBAction) request_classe_mapping;
-(IBAction) adozione_mapping;
-(IBAction) request_adozione_mapping;

@end

@interface Adozione: NSManagedObject
-(IBAction) save_to_backend;

@end

@interface Appunto: NSManagedObject
-(IBAction) data;
-(IBAction) note_e_righe;
-(IBAction) remove;

@end

@interface Classe: NSManagedObject
-(IBAction) giornoSection;
-(IBAction) updated_at;
-(IBAction) save_to_backend;
-(IBAction) giorno_modifica;

@end

@interface Cliente: NSManagedObject
-(IBAction) provincia_e_comune;
-(IBAction) save_to_backend;
-(IBAction) whichGroup;
-(IBAction) citta;
-(IBAction) title;
-(IBAction) coordinate;
-(IBAction) mapItem;
-(IBAction) sum_copie;

@end

@interface Coordinates
-(IBAction) initialize:(id) attrs;
-(IBAction) to_cl;

@end

@interface Docente
-(IBAction) initialize:(id) attributes;

@end

@interface Libro: NSManagedObject
@end

@interface Riga: NSManagedObject
@end

@interface Store
-(IBAction) client;
-(IBAction) setupReachability;
-(IBAction) context;
-(IBAction) persistent_context;
-(IBAction) store;
-(IBAction) backend;
-(IBAction) save;
-(IBAction) persist;
-(IBAction) clear;
-(IBAction) stats;
-(IBAction) initialize;

@end

@interface AppuntoCell: UITableViewCell

@property IBOutlet id labelDestinatario;
@property IBOutlet id labelNote;
@property IBOutlet id labelTotali;
@property IBOutlet id imageStatus;

@end

@interface AppuntoCellAuto: UITableViewCell
-(IBAction) get_height:(id) appunto;
-(IBAction) updateFonts;
-(IBAction) updateConstraints;

@end

@interface ClienteCell: UITableViewCell

@property IBOutlet id clienteLabel;
@property IBOutlet id cittaLabel;
@property IBOutlet id colorButton;

@end

@interface LibroCell: UITableViewCell

@property IBOutlet id imageCopertina;
@property IBOutlet id labelTitolo;
@property IBOutlet id labelPrezzoCopertina;
@property IBOutlet id buttonAdd;

-(IBAction) pushAddButton:(id) sender;

@end

@interface RigaCell: UITableViewCell
-(IBAction) riga;

@end

@interface CircleButton: UIButton
-(IBAction) setColor:(id) color;
-(IBAction) nel_baule;
-(IBAction) drawRect:(id) rect;

@end

