// Generated by IB v0.3.5 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError
@end

@implementation NSNotificationCenter
@end

@implementation NSURLRequest
@end

@implementation Camera
@end

@implementation UIAlertView
@end

@implementation ClickedButton
@end

@implementation InvalidURLError
@end

@implementation InvalidFileError
@end

@implementation Layout
@end

@implementation NSMutableURLRequest
@end

@implementation NSString
@end

@implementation NSURL
@end

@implementation UIImageView
@end

@implementation HTTPResult
@end

@implementation ClientDSL
@end

@implementation AFHTTPClient
@end

@implementation HeaderWrapper
@end

@implementation UIImage
@end

@implementation AnimationChain
@end

@implementation UIView
@end

@implementation Anonymous
@end

@implementation NSObject
@end

@implementation NSDictionary
@end

@implementation AnonymousArray
@end

@implementation NSArray
@end

@implementation NSString
@end

@implementation NSMutableString
@end

@implementation NSAttributedString
@end

@implementation NSMutableAttributedString
@end

@implementation Symbol
@end

@implementation Fixnum
@end

@implementation NSArray
@end

@implementation NSString
@end

@implementation Symbol
@end

@implementation UIColor
@end

@implementation UIImage
@end

@implementation Symbol
@end

@implementation SugarCubeNotFoundException
@end

@implementation NSError
@end

@implementation NSIndexPath
@end

@implementation NSLayoutConstraint
@end

@implementation NSNotification
@end

@implementation NSSet
@end

@implementation NSURL
@end

@implementation UIColor
@end

@implementation UIEvent
@end

@implementation UILabel
@end

@implementation UITextField
@end

@implementation UITouch
@end

@implementation UIView
@end

@implementation UIViewController
@end

@implementation CLLocationCoordinate2D
@end

@implementation UIControl
@end

@implementation UITextView
@end

@implementation UIActionSheet
@end

@implementation UIActivityIndicatorView
@end

@implementation UIAlertView
@end

@implementation UIBarButtonItem
@end

@implementation UIButton
@end

@implementation UISegmentedControl
@end

@implementation NSString
@end

@implementation NSArray
@end

@implementation NSIndexPath
@end

@implementation NSIndexSet
@end

@implementation NSString
@end

@implementation NSURL
@end

@implementation UIView
@end

@implementation CIColor
@end

@implementation CIFilter
@end

@implementation CIImage
@end

@implementation UIColor
@end

@implementation UIImage
@end

@implementation IndexPath
@end

@implementation NSError
@end

@implementation NSCoder
@end

@implementation NSData
@end

@implementation NSString
@end

@implementation NSURL
@end

@implementation Numeric
@end

@implementation String
@end

@implementation Fixnum
@end

@implementation NSDate
@end

@implementation NSString
@end

@implementation NSUserDefaults
@end

@implementation Object
@end

@implementation NilClass
@end

@implementation NSArray
@end

@implementation NSDictionary
@end

@implementation Fixnum
@end

@implementation NSString
@end

@implementation Numeric
@end

@implementation NSArray
@end

@implementation NSAttributedString
@end

@implementation NSString
@end

@implementation Symbol
@end

@implementation UIImage
@end

@implementation UILabel
@end

@implementation UIView
@end

@implementation UIViewController
@end

@implementation UINavigationController
@end

@implementation UITabBarController
@end

@implementation UIWebView
@end

@implementation Symbol
@end

@implementation NSString
@end

@implementation Base
@end

@implementation FormController
@end

@implementation FormableController
@end

@implementation InvalidClassError
@end

@implementation InvalidSectionError
@end

@implementation NoRowTypeError
@end

@implementation Conditions
@end

@implementation Form
@end

@implementation Form
@end

@implementation Object
@end

@implementation NSData
@end

@implementation UIActionSheet
@end

@implementation UITextField
@end

@implementation UITextField_Delegate
@end

@implementation UITextView
@end

@implementation UITextView_Delegate
@end

@implementation UITextView
@end

@implementation Row
@end

@implementation BackRow
@end

@implementation Base
@end

@implementation ButtonRow
@end

@implementation CheckRow
@end

@implementation CurrencyRow
@end

@implementation DateRow
@end

@implementation EditRow
@end

@implementation EmailRow
@end

@implementation ImageRow
@end

@implementation MapRowData
@end

@implementation MapRow
@end

@implementation NumberRow
@end

@implementation ObjectRow
@end

@implementation OptionsRow
@end

@implementation PagedImageRow
@end

@implementation PhoneRow
@end

@implementation PickerRow
@end

@implementation SliderRow
@end

@implementation StaticRow
@end

@implementation StringRow
@end

@implementation SubformRow
@end

@implementation SubmitRow
@end

@implementation SwitchRow
@end

@implementation TagsRow
@end

@implementation TemplateRow
@end

@implementation TextRow
@end

@implementation WebViewRow
@end

@implementation Section
@end

@implementation AppDelegate
@end

@implementation ALViewController
@end

@implementation AppuntiController
@end

@implementation AppuntoFormController
@end

@implementation ClienteDetailController
@end

@implementation ClienteFormController
@end

@implementation ClientiController
@end

@implementation DetailController
@end

@implementation DynamicController
@end

@implementation DynamicNewController
@end

@implementation EditListController
@end

@implementation EditPrezzoViewController
@end

@implementation EditReminderController
@end

@implementation EditStatoViewController
@end

@implementation EditTextFieldController
@end

@implementation EditTextViewController
@end

@implementation LibriController
@end

@implementation LibroAddController
@end

@implementation LibroFormController
@end

@implementation LoginController
@end

@implementation MainController
@end

@implementation MenuController
@end

@implementation RigaFormController
@end

@implementation ScanController
@end

@implementation SearchClienteController
@end

@implementation CredentialStore
@end

@implementation DataImporterResult
@end

@implementation DataImporter
@end

@implementation EKEventEditViewController
@end

@implementation NSArray
@end

@implementation NSEntityDescription
@end

@implementation NSIndexPath
@end

@implementation NSManagedObject
@end

@implementation NSManagedObject
@end

@implementation NSManagedObject
@end

@implementation Time
@end

@implementation UIBarButtonItemPlain
@end

@implementation UIBarButtonItemEdit
@end

@implementation UIBarButtonItemAdd
@end

@implementation UIBarButtonItemDone
@end

@implementation UIBarButtonItemCancel
@end

@implementation UINavigationControllerDoneCancel
@end

@implementation UITableView
@end

@implementation UITableViewCell
@end

@implementation UITableViewController
@end

@implementation UITableViewControllerForNSManagedObject
@end

@implementation UITableViewTextFieldCell
@end

@implementation UITableViewTextViewCell
@end

@implementation UIView
@end

@implementation MappingProvider
@end

@implementation Adozione
@end

@implementation Appunto
@end

@implementation Classe
@end

@implementation Cliente
@end

@implementation Coordinates
@end

@implementation Docente
@end

@implementation Libro
@end

@implementation Riga
@end

@implementation SecureMessage
@end

@implementation Store
@end

@implementation UserAuthenticator
@end

@implementation AppuntoCell
@end

@implementation AppuntoCellAuto
@end

@implementation ClienteCell
@end

@implementation LibroCell
@end

@implementation RigaCell
@end

@implementation RigaCellIb
@end

@implementation TotaliCellIb
@end

@implementation CircleButton
@end

@implementation HeaderCliente
@end

